Accessibility Issue creation
umbraco/HacktoberfestActivityLog pull request #82
Opened 2023-10-30 17:24 UTC by Truealex4

2023-10-31 08:35 UTC, busrasengul commented on README.md
> +- 2023-10-30 - [Alex Lovell](https://github.com/Truealex4) - Accessibility testing of v10 CMS and raising issue - Issue #15071 https://github.com/umbraco/Umbraco-CMS/issues/15071 - 'Select All' butto
```suggestion
```

2023-10-31 08:35 UTC, busrasengul commented on README.md
> +- 2023-10-30 - [Alex Lovell](https://github.com/Truealex4) - Accessibility testing of v10 CMS and raising issue - Issue #15070 https://github.com/umbraco/Umbraco-CMS/issues/15070 - contrast issue on
```suggestion
```

2023-10-31 08:35 UTC, busrasengul commented on README.md
> +- 2023-10-30 - [Alex Lovell](https://github.com/Truealex4) - Accessibility testing of v10 CMS and raising issue - Issue #15069 https://github.com/umbraco/Umbraco-CMS/issues/15069 - Umbraco logo is mi
```suggestion
```

2023-10-31 08:35 UTC, busrasengul commented on README.md
> +- 2023-10-30 - [Alex Lovell](https://github.com/Truealex4) - Accessibility testing of v10 CMS and raising issue - Issue #15068 https://github.com/umbraco/Umbraco-CMS/issues/15068 - Media library is m
```suggestion
```

2023-10-31 08:36 UTC, busrasengul commented on README.md
> +- 2023-10-30 - [Alex Lovell](https://github.com/Truealex4) - Accessibility testing of v10 CMS and raising issue - Issue #15067 https://github.com/umbraco/Umbraco-CMS/issues/15067 - Contrast issue upo
```suggestion
- 2023-10-30 - [Alex Lovell](https://github.com/Truealex4) - Accessibility testing of v10 CMS and raising issues - [Issues](https://github.com/umbraco/Umbraco-CMS/issues?q=is%3Aissue+author%3ATruealex4+created%3A2023-10-01..2023-10-31+accessibility)
```

2023-10-31 08:38 UTC, busrasengul requested changes
Let's merge all the issues in one place and link them to the relevant link in the issue tracker :)
This way it's easier to review for all the issues!
Thanks a lot @Truealex4

2023-10-31 11:05 UTC, busrasengul commented
Perfect now! Let's get this merge in 🎉

2023-10-31 11:05 UTC, merged

2023-11-24 15:18 UTC, Alex-Lovell commented
Hi Seb,

Yeah, I got some feedback that people who didn’t know who the real Alex Lovell was!

Have a great weekend.

Alex

From: Sebastiaan Janssen ***@***.***>
Sent: Friday, November 24, 2023 3:15 PM
To: umbraco/HacktoberfestActivityLog ***@***.***>
Cc: Alex Lovell ***@***.***>; Mention ***@***.***>
Subject: Re: [umbraco/HacktoberfestActivityLog] Accessibility Issue creation (PR #82)


@Alex-Lovell<https://github.com/Alex-Lovell> I noticed you changed your GitHub username, so the @Truealex4 was supposed to be for you 😅

—
Reply to this email directly, view it on GitHub<https://github.com/umbraco/HacktoberfestActivityLog/pull/82#issuecomment-1825808117>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXOYYN4RNQGE3JFD4QC5VBDYGC2YZAVCNFSM6AAAAAA6WMOHIOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRVHAYDQMJRG4>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>